### ISSUE TITLE
Treinamento Git

### ISSUE THREAD

**Issue by AmandaMuniz** [fga-eps-mds/2019.1-Gaia#1]
Nessa issue deverá ser feito:

- Treinamento de Git para os membros de MDS.

Critérios de aceitação:

- [x] Todos os integrantes de MDS devem saber como utilizar o git de acordo com o guia de contribuição.

**Comment by CalebeRios** [comment]
Um treinamento já foi feito no dia 16/03/2019. A apresentação pode ser encontrado nesse [link](https://docs.google.com/presentation/d/16PosOV1uZU5rZIGDysZ5whBV2K7hJ8F3qv8hO2YU4WI/edit?usp=sharing).
