### ISSUE TITLE
Daily Sprint 4 (13/04 a 20/04)

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#111]
Essa issue tem como objetivo registrar as dailies remotas do time na Sprint 4

**Comment by lucianaribeiro** [comment]
Até o momento estava estudando para as outras matérias e por isso finalizei apenas a documentação do planejamento  da sprint 4. Ainda hoje enviarei os resultados da sprint 3. Nao tenho dificuldade em realizar minhas issues, apenas falta de tempo.

**Comment by Ed-vL** [comment]
Estive pesquisando sobre a requisição de um container ao outro, ainda não cheguei em uma boa solução. Primeira issue da sprint foi fechada.

**Comment by AmandaMuniz** [comment]
@lucianaribeiro Ontem eu continuei estudando sobre a integração dos microsserviços. Hoje fiz os diagramas de pacotes que precisam existir, fiz uma atualização da nossa arquitetura. E estou fazendo a revisão do documento de arquitetura. Acho que consigo finalizar essa issue hoje, para conseguir me dedicar a integração o restante da sprint.

**Comment by micaellagouveia** [comment]
Hoje me encontrei com a Sofia e nós adicionamos a classe clima, e já atribuimos os valores do json para as variáveis criadas. Fizemos uma busca para fazer o tratamento das variáveis, e finalizamos essa issue amanha. A issue do bot, pretendemos finalizar sexta para colhermos mais historias, mas o bot já responde tudo o q perguntamos.

**Comment by SamButers** [comment]
Da mesma forma que o Eduardo e o Luís, estive pesquisando como realizar a conexão entre os dois microserviços não utilizando o --network="host".

**Comment by sofiapatrocinio** [comment]
Hoje pareei com a Micaella, fizemos a model da Gaia Clima e criamos a classe, estamos separando os atributos da classe para tratá-los e finalizaremos amanhã. Estamos testando a Gaia com vários usuários, afim de aumentar sua fluidez de conversa.

**Comment by LhTaira** [comment]
Assim como Samuel e Edu tenho pesquisado sobre como funcionam redes em containers do docker tentando arrumar outra solução para o problema de um container não conseguir se comunicar com o outro por localhost que não seja por --network. Sem sucesso.

**Comment by inddiara** [comment]
@lucianaribeiro Consegui marcar uma reunião com o Marcelo pra semana que vem. Ele é expert no assunto e vai nos ajudar com a parte de análise dos dados pra recomendar esportes. Além disso, comecei revisar o doc de visão e consolidar umas infos que achei sobre as condições propícias pra prática de modalidades ao ar livre

**Comment by CalebeRios** [comment]
@lucianaribeiro Eu estou estudando e testando o Rancher, mas não muito sucesso. Amanhã vou sentar com o Diniz e ele vai me ajudar, então amanhã provavelmente teremos o deploy! Eu terminei de migrar a integração continua páramo GitLab ci, mas o projeto do Local está com os testes quebrando, então teremos que tirar um tempo para rever esses testes. Amanhã irei finalizar o deploy, e já começar o Docker de esporte, pois acho que próxima Sprint vamos começar ele

**Comment by LhTaira** [comment]
Junto com Samuel e Edu implementamos a solução sugerida pelo Miranda para fazer requisição entre dois containers usando o ip da máquina. Fizemos também um método para colocar o ip da máquina em uma variável de ambiente automaticamente, o que não funcionava para Windows e deixava o comando de run muito longo. Hoje nós tiramos essa automatização e colocamos no README instruções para o usuário colocar seu próprio IP.

**Comment by micaellagouveia** [comment]
Eu e a sofia terminamos o tratamento das variáveis, estamos agora separando esse tratamento em um arquivo a parte. Faremos os testes depois de separar.

**Comment by Ed-vL** [comment]
@lucianaribeiro Encontramos mais problemas com a comunicação entre as API, devido às rede. Uma solução encontrada foi utilizar o IP da máquina local, mas ainda estamos estudando soluções melhores

**Comment by SamButers** [comment]
Junto com a equipe, refizemos o que foi feito na sprint passada da conexão com clima e local e resolvemos o que faltava para entregar a issue, sendo os testes serem feitos de maneira melhor, adaptar o código para não ferir a arquitetura e os problemas com a conexão dos dois dockers.

**Comment by sofiapatrocinio** [comment]
Terminamos de tratar os dados, faltam os testes

**Comment by AmandaMuniz** [comment]
@lucianaribeiro Ontem eu terminei de refatorar o doc de arquitetura. Agora temos um diagrama de classe. Como informei ao time, hoje eu só vou conseguir trabalhar lá para as 23h. Devo finalizar a decisão sobre a integração contínua nesse horário.

**Comment by inddiara** [comment]
@lucianaribeiro Eu estou finalizando o protótipo de alta fidelidade da Gaia e jaja vou documentar ele na wiki

**Comment by lucianaribeiro** [comment]
Eu enviei a documentação do resultado da sprint 3 e o planejamento da sprint 4. O documento de riscos está sendo feito. 
Além disso propus ao time que a reunião da sprint seja feita pela manhã porque eu e Calebe não poderemos comparecer de tarde.

**Comment by lucianaribeiro** [comment]
@sofiapatrocinio @micaellagouveia quando pretendem abrir o PR?

**Comment by micaellagouveia** [comment]
Estamos tendo dificuldades para implelementar os testes.

**Comment by CalebeRios** [comment]
@lucianaribeiro Opa, hora da daily. Hoje eu finalizei o deploy para homologação do clima e do local (Ainda precisa de algumas alterações no código do clima), mas é rapidinho. Hoje a noite eu mexi em arrumar o gitlab ci do clima
