### ISSUE TITLE
US09 - Eu como usuário desejo que a Gaia forneça os dados corretos a respeito de clima

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#124]
Nessa issue será realizado:
- [x] Adicionar slots nas entidades
- [x] Tratar slots
- [x] Configurar uma custom action genérica na Gaia
- [x] Transformar custom action genérica em específica

Critérios de aceitação:
- [ ] Na mensagem de resposta da Gaia, inserir o local referente a esse clima
- [ ] Exibir informações de temperatura, rajadas de vento, pressão atmosférica, umidade
- [ ] Perguntar se o usuário deseja saber mais dados 
- [ ] Se ele disser que sim, então exibir todos os outros dados advindos da API

**Comment by lucianaribeiro** [comment]
Essa issue deve ser feita até dia 23/04

**Comment by Ed-vL** [comment]
Sobre a conexão da Gaia com a API do clima, vamos dar um get direto à API rodando em localhost?

**Comment by sofiapatrocinio** [comment]
Estamos com problemas nas custom actions, depois de atualizar o que ela deve fazer, a ação que está retornando é a mesma. Estamos vendo como funciona o servidor das custom actions para alterar isso
