### ISSUE TITLE
US11 - Eu como usuário desejo que o sistema consiga filtrar o esporte de acordo com as condições meteorológicas

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#126]
Nessa issue será realizado:

- [x] Fazer conexão com o MongoDB
- [x] Criar schema e a model
- [x] Fazer a task para salvar os esportes no banco
- [x] Comparar o esporte com o clima atual
- [x] Retornar para o usuário os esportes

Critérios de aceitação:
- [ ] Estar testado
- [ ] Eslint sem warnings e erros
- [ ] O esporte só deve ser recomendado se os três parâmetros (temperatura, velocidade do vento e umidade) estiverem dentro no intervalo
- [ ] Fluxo alternativo: se apenas dois parâmetros estiverem em concordância com os intervalos ideais, então a Gaia deve sugerir as modalidades com uma msg de ressalva
- [ ] Fluxo alternativo 2: se apenas um parâmetro estiver de acordo com os intervalos ideais, então a Gaia deve retornar uma msg de alerta

**Comment by inddiara** [comment]
A velocidade do vento neste projeto é expressa em nós, que correspondem a uma milha náutica por hora (1 nó = 1.852 km / h = 0,514 m / s). "Nós" é a principal unidade usada para atividades marítimas e esportes aquáticos @micaellagouveia @LhTaira

**Comment by LhTaira** [comment]
@inddiara Estamos precisando de informações sobre quais condições deverão ser avaliadas para a recomendação de cada esporte.

**Comment by inddiara** [comment]
Como havia comentado na daily, a tabela de parâmetros pode ser acessada pela branch da issue #137. Assim que o PR for aceito, esse link estará disponível no deploy da wiki
