### ISSUE TITLE
US14 - Eu como usuario desejo que a gaia consiga guardar meus dados e minhas preferencias

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#152]
Nessa issue será realizado:
- [x] criar usuário com seus atributos
- [x] Salvar dados do usuário no banco
- [x] Receber os dados do usuário pelo Rasa

Critérios de aceitação:
- [x] Estar testado
- [x] Eslint sem erros e warnings
- [x] Salvar dados de usuário no banco
- [x] Salvar preferência de dia e horário que o usuário deseja ser notificado

**Comment by LhTaira** [comment]
O que foi feito no gaia notifica está diferente do diagrama de classe

É melhor que o diagrama seja modificado para que as preferências do usuário sejam salvas no modelo de usuário ou que o gaia-notifica salve as preferências crie um objeto notificação para cada usuário?

**Comment by AmandaMuniz** [comment]
As mudanças feitas serão aceitas e o diagrama de classe será refatorado

**Comment by Ed-vL** [comment]
Alteramos os atributos de dia, hora, local e esporte para Array, com o intuito de ser possível ao usuário salvar mais de um dia, hora, local e esporte.
