### ISSUE TITLE
US15 - Eu como usuário desejo que a gaia me informe se um determinado esporte é favorável de ser realizado ou não 

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#153]
Nessa issue será realizado:
- [x] Criar intents para esportes específicos
- [x] Criar custom action
- [x] Fazer busca no json
- [x] Tratar respostas de favoráveis

Critérios de aceitação:
- [x] A Gaia deve entender quando o usuário perguntar se pode praticar esporte "x" em lugar "y"
- [x] A Gaia deve informar se praticar esporte x está 100% favorável, ou com ressalva ou com alerta
- [x] Caso o esporte x perguntado pelo usuário esteja 0% favorável, a Gaia deve informar quais outras modalidades estão para aquele lugar informado

**Comment by sofiapatrocinio** [comment]
Já terminamos todas funcionalidades, porém com código duplicado nas actions. Estamos tendo alguns problemas com importação de custom actions e veremos amanhã mais descansados

**Comment by sofiapatrocinio** [comment]
Issue já em revisão. Nomeamos a branch errado, ao invés de "#153", está como issue "#157", mas já mandamos o Pull Request, e está relacionada a issue certa
