### ISSUE TITLE
Olhar todos os serviços e ver o que precisa ser melhorado

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#168]
Nessa issue será realizado:
- Olhar todos os repositórios e levantar melhorias

Critérios de aceitação:
- [X] Possíveis melhorias comentadas na issue

**Comment by CalebeRios** [comment]
Criar uma issue para tudo isso, tratar cada ponto desse como um critério de aceitação[3]:

- No arquivo action_local, na função weatherRequest, é necessário revisar espaçamento dentro do if.
 - No método run do Action_local, é necessário revisar quebras de linha desnecessária.
 - A action_sport esta repetindo o mesmo código que esta no action_local. Cada um deve ter sua responsabilidade.
 - Rever quebras de linha no action_sport
 - Os métodos run do action_weather faz o dispatcher de uma forma duplicada, arrumar essa parte.
 - Rever espaços e quebra de linhas no action_weather

**Comment by CalebeRios** [comment]
Criar uma issue para tudo isso, tratar cada ponto desse como um critério de aceitação [3]:

- Criar as endpoints na rota principal.
 - Rever todos os nomes dos arquivos. (alguns com nomes faltando, sem um padrão nos nomes)
 - Variáveis mais significativas em routes.
 - A pasta config só serve para o banco, então poderia estar dentro de db.
 - dbAction é um nome nada significativo.
 - Não é necessário ficar esperando salvar item por item no banco, isso pode ser assincrono.
- O schema não deve estar jogando em db. Cada pasta deve ter sua responsabilidade.
- Em sportsSchema: temperature, humidity e windSpeed podem ser um array direto, e não um objeto com um array.
 -  Nomes de testes nada significativo
 - Arquivos não possui a nomenclatura correta. E possui quebra de linhas desnecessária.
- treatmentWeather, passar alguns ifs para when

**Comment by CalebeRios** [comment]
Criar uma issue para tudo isso, tratar cada ponto desse como um critério de aceitação[3]:

- Criar as endpoints na rota principal.
 - Rever todos os nomes dos arquivos. (alguns com nomes faltando, sem um padrão nos nomes)
 - Variáveis mais significativas em routes.
 - A pasta config só serve para o banco, então poderia estar dentro de db.
- O schema não deve estar jogando em db. Cada pasta deve ter sua responsabilidade.
 -  Nomes de testes nada significativo
 - Arquivos não possui a nomenclatura correta. E possui quebra de linhas desnecessária.
