### ISSUE TITLE
Estudar EVM

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#170]
Nessa issue será realizado:
- [x] Estudar o que é EVM
- [x] Consultar outros projetos para entender como utilizar essa métrica

Critérios de aceitação:
- [x] PO e Tech lead concluído a leitura

**Comment by inddiara** [comment]
https://blogpilates.com.br/valor-agregado/

**Comment by inddiara** [comment]
https://www.projectbuilder.com.br/blog/analise-de-valor-agregado/

**Comment by inddiara** [comment]
https://www.projectbuilder.com.br/blog/o-que-e-gestao-de-valor-agregado-gva-e-qual-a-importancia-dele-para-a-minha-empresa/

**Comment by inddiara** [comment]
https://pt-br.eventials.com/tecnospeed/webinar-como-aumentar-o-valor-agregado-do-seu-software/
