### ISSUE TITLE
Definir tarefas que serão feitas na API Gateway

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#175]
Nessa issue será realizado:
- [x] Codar um exemplo de Gateway
- [x] Definir tarefas do Gateway
- [x] Disponibilizar comentário explicando as tarefas do Gateway

Critérios de aceitação:
- [x] Explicar o funcionamento de um Gateway para MDS

**Comment by AmandaMuniz** [comment]
## O que será necessário ser feito no Gaia-Gateway

Para a criação de uma Api Gateway é preciso ter os seguintes files:

- index.js

Pacote routes:
- router.js - responsável por combinar os endpoints de todos os serviços.
- routerAdapter - responsável por construir os endpoints de cada serviço.
- gaiaClimaRouter - responsável por redirecionar a requisição para o Gaia-Clima.
- gaiaLocalRouter - responsável por redirecionar a requisição para o Gaia-Local.

Pacote controller:
- Files que irão lidar com a autenticação e autorização.

Para o Gaia-Gateway é importante levar em conta que as requisições enviadas pela Gaia precisam ser quebradas em pequenas requisições. Para isso ser feito é preciso ler o conteúdo da requisição e enviar somente os dados pertinentes para cada microsserviço. 

O processo inverso precisa ser feito para as requisições que vem dos microsserviços. Elas precisam montar uma resposta completa para que posse ser mandado para o usuário. Portanto, é importante saber identificar as requisições e de onde elas fazem parte. Então, criar um meio de identificação é necessário.

Por último, é preciso levar em consideração a ordem de prioridade das requisições. Uma requisição ao Gaia-Local deve ter prioridade maior que uma requisição para Gaia-Clima, já que é preciso dos dados de local para Gaia-Clima retornar as informações pertinentes. Portanto, na divisão da requisição é preciso trabalhar com essa prioridade.

A decisão das tarefas que o Gaia-Gateway irá realizar foram criadas levando em consideração as seguintes referências:

>https://blog.risingstack.com/building-an-api-gateway-using-nodejs/
>https://hackernoon.com/creating-simple-api-gateway-using-node-js-6d5933c214b8
>https://www.luiztools.com.br/post/api-gateway-em-arquitetura-de-microservices-com-node-js/
>https://medium.com/sharenowtech/k-fastify-gateway-a-node-js-api-gateway-that-you-control-e7388c229b21
