### ISSUE TITLE
US16-Eu como usuário desejo agendar uma notificação

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#176]
Nessa issue será realizado:
- [x] Adicionar função de notificação
- [x] Salvar notificação no banco de dados
- [x] Criar fluxo na Gaia

Critérios de aceitação:
- [x] Usuário conseguir agendar uma notificação
- [x] Notificação deve ser salva no banco
- [x] Gaia deve responder que a notificação foi salva com sucesso
- [x] Eslint sem erros e warnings
- [x] Respeitar folha de estilo do Rasa (flake8)
- [x] Estar testado

**Comment by sofiapatrocinio** [comment]
O rasa apresentou problema para armazenar mais de um slot, no caso de salvar uma notificação para dois dias, precisamos pegar preferência do usuário como um array: terça e quinta, por exemplo. Quando o tipo de slot é mudado para 'list', aparece "AttributeError: 'list' object has no attribute 'expandtabs'". Ao procurar o erro, vi que pode ser um problema da versão do Rasa Core: https://forum.rasa.com/t/not-able-to-export-stories-using-interactive-learning-rasa-version-core-0-13-0-nlu-0-14-1/4835

**Comment by AmandaMuniz** [comment]
Escrevam as tasks que fizeram nessa issue
