### ISSUE TITLE
US18-Eu como usuário desejo que o sistema Gateway seja capaz de gerenciar minhas requisições de esporte

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#178]
Nessa issue será realizado:
- [x] Receber requisição da Gaia
- [x] Quebrar requisição maior e priorizar as menores
- [x] Enviar cada requisição menor para o microsserviço correspondente.
- [x] Receber respostas dos microsserviços e montar resposta final que será enviado para o usuário.
- [x] Testar

Critérios de aceitação:
- [x] Redirecionar requisições p/ os microserviços
- [x] Estar testado
- [x] Eslint sem erros e warnings

**Comment by AmandaMuniz** [comment]
Para a realização dessa issue vocês precisam realizar as tarefas abaixo:

- [ ] Receber requisição da Gaia
- [ ] Quebrar requisição maior e priorizar as menores
- [ ] Enviar cada requisição menor para o microsserviço correspondente.
- [ ] Receber respostas dos microsserviços e montar resposta final que será enviado para o usuário.
- [ ] Testar

Eu tomei a liberdade de adicionar essa lista nas tasks de vocês.

**Comment by AmandaMuniz** [comment]
Vocês podem encontrar uma explicação mais detalhada do que precisa ser feito nessa [issue](https://github.com/fga-eps-mds/2019.1-Gaia/issues/175). Lá eu expliquei qual deve ser a lógica por trás de toda nossa Api Gateway, e como os pacotes devem ser. Qualquer dúvida vocês podem me perguntar e lembrem-se que essa issue só vai lidar com a requisição de esportes.
