### ISSUE TITLE
US19 -Eu como usuário desejo que a Gaia me responda com mais acurácia e precisão

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#179]
Nessa issue será realizado:
- [x]  Melhorar conversação da Gaia

Critérios de aceitação:
- [x] A Gaia deve compreender e responder o usuário da maneira adequada

**Comment by sofiapatrocinio** [comment]
Estou implementando testes de conversação, porém como nosso deploy está fora do ar, não estão funcionando
