### ISSUE TITLE
Definir microsserviço do ciclone 

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#180]
Nessa issue será realizado:
- [x] Garantir viabilidade técnica
- [x] Definir api's externas
- [x] Definir tecnologias
- [x] Explicar nos documentos necessários

Critérios de aceitação:
- [x] Estar documentado na wiki

**Comment by AmandaMuniz** [comment]
Para garantir uma solução tecnicamente viável para o microsserviço do ciclone, será utilizado incialmente a API Externa [Aeris Weather](https://www.aerisweather.com/support/docs/api/). Ela contém um endpoint chamado /tropicalcyclones que retorna todos os ciclones ativos, com dados sobre eles e o local onde estão passando. Essa api é grátis apenas por dois meses e tem um limite de requisição. Mas como foi a única api encontrada, até o momento, que garante a viabilidade técnica do microsserviço, será utilizada até uma nova solução ser definida.

**Comment by AmandaMuniz** [comment]
A api Aeris Weather retorna o local em que o ciclone se encontra com coordenadas geográficas. Por isso, a api [OpenCage Geocoder](https://opencagedata.com/demo) será utilizada para retornar o nome da localidade.

**Comment by AmandaMuniz** [comment]
Visando garantir o menor risco as tecnologias que serão utilizadas são as mesmas do microsserviço já existente. Ou seja, nodeJS e mongoDB. O mongo é necessário porque os agendamentos de notificação devem ser salvos.

**Comment by AmandaMuniz** [comment]
O microsserviço será um cronjob de notificação. Portanto, deverá ser feito um algoritmo que a cada determinado intervalo de tempo, faça uma requisição a APi Aeris Weather para verificar a ocorrência de ciclones. Se for identificado um evento, isso deve ser notificado aos usuários que possuem preferência por esse tipo de notificação.

**Comment by AmandaMuniz** [comment]
Todas as informações referentes ao novomicrosserviço poderão ser encontradas no documento de arquitetura e no documento de definição de arquitetura.
