### ISSUE TITLE
US23: Eu como usuário desejo que o sistema me notifique quando eu desejar

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#190]
Nessa issue será realizado:
- [x] Adicionar campo para saber quanto tempo antes o user quer ser notificado
- [x] Notificar o user na Gaia
- [x] Colocar notificação como esquema principal no mongo

Critérios de aceitação:
- [ ] O sistema deve entender o formato que o usuário inserir (por ex: 12:00, 12h00, meio dia)
- [x] O sistema também deve entender quando o usuário pedir que seja notificado na data x, horário y
- [x] Exibir a notificação para o usuário na data escolhida por ele

**Comment by Ed-vL** [comment]
Sobre a mudança no banco para usar a notificação como esquema principal. Ainda será necessário a existência da classe User? Levando em consideração que a notificação já possui telegramID, que é o que utilizamos para identificar um usuário.

**Comment by CalebeRios** [comment]
@Ed-vL Não é necessário a classe user, pode deixar somente o telegramID

**Comment by Ed-vL** [comment]
O usuário agora poderá especificar quanto tempo antes quer ser notificado. Para isso, vamos padronizar esse tempo pedido? Deixando o tempo sempre em minutos por exemplo.

**Comment by AmandaMuniz** [comment]
@Ed-vL O padrão é hora:minuto. Mas a PO espera que o usuário possa escrever 12h30, 12:30 e meio-dia e meia, para que agregue valor ao produto.

**Comment by Ed-vL** [comment]
Mas no caso de o usuário desejar salvar o horário 12h30 e ser notificado 1h antes, esse 1h antes será padronizado? Deixando 60min na requisição, neste caso.

**Comment by AmandaMuniz** [comment]
@Ed-vL Você tem que receber isso tanto em horas quanto em minutos e pode padronizar para um dos dois internamente

**Comment by Ed-vL** [comment]
@AmandaMuniz Sobre a notificação, preciso mandar na mensagem ao usuário se o esporte é favorável? Teria que mandar o clima também? E a notificação pode ter mais de um local mesmo?

**Comment by CalebeRios** [comment]
@Ed-vL Sim, é necessário mandar esporte e clima juntos. Essa parte do Clima quem esta fazendo é o @Luistaira, ele criou 3 rotas em clima para pegar isso, se alinhe com ele para ficar correto.

**Comment by lucianaribeiro** [comment]
Essa issue será entregue até dia 28/05
