### ISSUE TITLE
Verificar a viabilidade de saber se a cidade é litorânea ou não

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#191]
Nessa issue será realizado:
- [x] Pesquisar métodos para saber se a cidade é litorânea

Critérios de aceitação:
- [x] Ter uma solução ou não para o bug do surfista em Brasília

**Comment by AmandaMuniz** [comment]
Até o momento não foi encontrada uma solução para cidades litorâneas. Uma pesquisa extensa foi feita para encontrar diferentes soluções. A única API externa encontrada que faz algo similiar ao desejado, só informa a distância entre o oceano e cidades americanas. A outra opção seria fazer isso na mão, porém listar todas as cidades litorâneas e adicionar uma flag para saber se é ou não litorânea é completamente inviável. Dito isso, nenhuma das escolhas vai ser feita, por nenhuma das duas garantir viabilidade técnica. Logo, o bug de indicar esportes que só podem ser feitos no mar para cidades que não estão próximas da costa, irá continuar existindo até que uma melhor solução seja encontrada.
