### ISSUE TITLE
Realizar alterações de melhoria no microsserviço Gaia-Clima

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#193]
- [x] Criar as endpoints na rota principal.
- [x] Rever todos os nomes dos arquivos. (alguns com nomes faltando, sem um padrão nos nomes)
- [x] Variáveis mais significativas em routes.
- [x] A pasta config só serve para o banco, então poderia estar dentro de db.
- [x] dbAction é um nome nada significativo.
- [x] Não é necessário ficar esperando salvar item por item no banco, isso pode ser assincrono.
- [x] O schema não deve estar jogando em db. Cada pasta deve ter sua responsabilidade.
- [x] Em sportsSchema: temperature, humidity e windSpeed podem ser um array direto, e não um objeto com um array.
- [x] Nomes de testes nada significativo
- [x] Arquivos não possui a nomenclatura correta. E possui quebra de linhas desnecessária.
- [x] treatmentWeather, passar alguns ifs para when

**Comment by AmandaMuniz** [comment]
Essa issue se refere a melhorias no Gaia-Clima, seria interessante mudar o nome dela.

**Comment by micaellagouveia** [comment]
No tópico 3, varáveis mais significativas seria o nome das rotas?

**Comment by CalebeRios** [comment]
@micaellagouveia Os nomes das variáveis mesmo, mas se achar que consegue melhorar os nomes das rotas, pode alterar também

**Comment by micaellagouveia** [comment]
No tópico 8, utilizamos as variáveis de temperatura, velocidade do vento e umidade como objeto pois todas elas guardam seus intervalos de condições favoráveis. Seria viável modificá-las?

**Comment by CalebeRios** [comment]
@micaellagouveia Modificar elas de que forma?

**Comment by micaellagouveia** [comment]
Pedem pra transformar em um array direto, e não um objeto.

**Comment by CalebeRios** [comment]
Entendi, mas faz sentido serem objetos ou arrays? Falo isso porque como você pode ter mais de um limite, isso tem cara de array.

**Comment by micaellagouveia** [comment]
o schema nao deve estar em db, então ela deve ter uma pasta específica?

**Comment by AmandaMuniz** [comment]
Cria uma pasta de schemas

**Comment by micaellagouveia** [comment]
ela fica direto na src? o ai excluiria a db? ou dentro da db?

**Comment by AmandaMuniz** [comment]
@micaellagouveia Dentro de src. Em db vão ficar só as actions
