### ISSUE TITLE
US24: Eu como usuário desejo que o Gateway trate minhas requisições

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#200]
Nessa issue será realizado:
- [x] Construir gateway
- [x] Criar rotas para os micro-serviços

Critérios de aceitação:
- [x] Gateway identificar quais requisições devem ser enviadas para cada micro-serviço
- [x] Para cada micro-serviço, utilizar apenas uma / junto com os parâmetros

**Comment by lucianaribeiro** [comment]
Essa issue foi retirada da sprint 9 devido às dívidas técnicas.

**Comment by AmandaMuniz** [comment]
Nessa US os parsers que estão na Gaia deverão ser transferidos para o Gateway
