### ISSUE TITLE
Passar Gaia-Clima para Gaia-Esporte - 22/5

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#204]
Nessa issue será realizado:
- [x] transferir pastas do Gaia-Clima para Gaia-Esporte
- [x] Refatorar  funções
- [x] Consertar rota climateForecast

Critérios de aceitação:
- [x] Estar funcionando como um microserviço só
- [x] Estar testado
- [x] Eslint sem erros e warnings

**Comment by sofiapatrocinio** [comment]
Estamos tendo problemas com o MongoDB, o Mongo original de esporte não fazia conexão e ao mudar para o de Local, as requisições deram problema.

**Comment by lucianaribeiro** [comment]
Essa issue será entregue dia 27/05
