### ISSUE TITLE
Melhorar fluxo da Gaia

### ISSUE THREAD

**Issue by AmandaMuniz** [fga-eps-mds/2019.1-Gaia#210]
Nessa issue será realizado:

- [x] Mudar o fluxo da Gaia para esporte ser o principal
- [x] Exibir lista com tudo que a Gaia pode fazer
- [x] Arrumar erros da folha de estilo

Critérios de aceitação:

- [x] Gaia dialogando com usuário e informando quais funcionalidades oferece
- [x] Melhor interatividade com usuário

**Comment by lucianaribeiro** [comment]
Essa issue será entregue dia 28/05
