### ISSUE TITLE
US27: Eu, como usuário, desejo manter minhas notificações 

### ISSUE THREAD

**Issue by AmandaMuniz** [fga-eps-mds/2019.1-Gaia#226]
Nessa issue será realizado:
- [x] Criar função visualizar notificação
- [x] Criar função deletar notificação
- [x] Criar função editar notificação
- [x] Adicionar funções no fluxo da Gaia 

Critérios de aceitação:
- [x] Eslint sem erros e warnings
- [x] Estar testado
- [x] Exibir botões para que o usuário selecione o que deseja fazer
- [x] Exibir todas as notificações salvas no banco pelo usuário
- [x] Gaia deve compreender a funcionalidade do CRUD selecionada

**Comment by sofiapatrocinio** [comment]
Na função editar, faz mais sentido o usuário passar todos os dados da nova notificação ou somente o(s) dado(s) que quer alterar?

**Comment by inddiara** [comment]
@sofiapatrocinio Visando a experiência do usuário de modo que ele não tenha dificuldades p realizar esse ação, é preferível que o usuário seja instruído a editar todos os atributos de sua notificação, pois editar apenas um ou outro tornaria a conversação confusa. Ao realizar a edição, a Gaia deve confirmar que foi concluído com sucesso e exibir os dados da notificação editada.

**Comment by sofiapatrocinio** [comment]
Ao terminar a issue, nos deparamos com alguns problemas de fluxo de conversa. Estamos resolvendo isso para melhorar experiência do usuário.
