### ISSUE TITLE
US26: Eu como usuário desejo que o sistema faça uma nova requisição a cada 2 horas 

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#232]
### US26: Eu como usuário desejo que o sistema faça uma nova requisição a cada 2 horas  

Nessa issue será realizado:
- [x] Fazer requisicao a cada 2 horas no repositório Ciclone
- [x] Tratar informações

Critérios de aceitação:
- [ ] Função que faz requisição a cada 2h
- [ ] Mostrar para o usuário a resposta obtida em cada requisição
- [ ] Eslint sem erros e warnings
- [ ] Estar testado

**Comment by AmandaMuniz** [comment]
Nessa issue deverá ser feito um algoritmo que faça requisições a API externa a cada duas horas. A documentação do endpoint que será utilizado se encontra nesse [link](https://www.aerisweather.com/support/docs/api/reference/endpoints/tropicalcyclones/)

**Comment by AmandaMuniz** [comment]
Além do algoritmo, deverá ser feito o tratamento das informações que a API retorna. Os campos que são importantes para a notificação são:

- origin
- currentbasin
- name
- startdate
- enddate
- stormtype
- stormspeed

Em currentbasin a API retorna abreviações, mas a PO espera que a Gaia retorne o nome completo ao usuário. Os demais campos devem conter tratamentos se necessário. Um maior detalhamento desses campos pode ser encontrado no supported query properties da API externa, disponivel nesse [link](https://www.aerisweather.com/support/docs/api/reference/endpoints/tropicalcyclones/)
