### ISSUE TITLE
US28: Eu como usuário desejo manter minhas notificações de ciclone

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#233]
### *US28: Eu como usuário desejo manter minhas notificações de ciclone*

Nessa issue será realizado:
- [x] Criar fluxo da Gaia
- [x] Opção de receber a notificação do ciclone
- [x] Opção de não receber a notificação do ciclone

Critérios de aceitação:
- [x] Gaia informar que pode criar um alerta de ciclone
- [x] Usuário conseguir deletar o alerta de ciclone
- [x] Gaia informar que o alerta foi criado com sucesso

**Comment by AmandaMuniz** [comment]
A notificação precisa conter, além do id do usuário, os seguintes itens:
- origin
- currentbasin
- name
- startdate
- enddate
- stormtype
- stormspeed

Um maior detalhamento desses campos podem ser encontrados no supported query properties da API externa, disponivel nesse [link](https://www.aerisweather.com/support/docs/api/reference/endpoints/tropicalcyclones/)

**Comment by AmandaMuniz** [comment]
Para a notificação de ciclone o usuário não passará informações extras. Ele só dirá se a quer ou não. Levar isso em consideração na hora de montar o fluxo.
