### ISSUE TITLE
Estudar testes de integração

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#234]
### *Estudar testes de integração*

Nessa issue será realizado:
- [x] Estudo de como um teste de integração é feito
- [x] Verificação se teste de integração já está sendo implementado

Critérios de aceitação:
- [x] Decisão sobre a realização dos testes de integração

**Comment by AmandaMuniz** [comment]
Durante os estudos sobre o tema, foi notado que um teste de integração funciona para verificar o status esperado de uma requisição. Por exemplo, em um método get feito corretamente é esperado status 200 como resultado. No contexto de microsserviços, esses testes seriam feitos para verificar a comunicação entre o Gateway e os microsserviços. A dificuldade de um teste de integração é na hora da pipeline de homologação, porque as tecnologias não conseguem entender que existe um outro container. É por isso que o custo de testes de integração são altos, já que ele exige que várias partes da aplicação estejam ativas e em execução ao mesmo tempo. E embora a importância dos testes de integração seja alta, não faz sentido ser implmentado nessa etapa do projeto. Por isso, outros testes, como unitários, serão feitos para suprir na cobertura de testes.
Links uteis para entender o assunto são:
https://medium.com/@mateus1198/como-fazer-os-testes-de-integra%C3%A7%C3%A3o-usando-chai-http-748e9d2e3017
https://br.atlassian.com/continuous-delivery/software-testing/types-of-software-testing
