### ISSUE TITLE
Documentar os resultados do teste de usabilidade

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#235]
### *Documentar os resultados do teste de usabilidade*

Nessa issue será realizado:
- Registrar resultados dos testes de usabilidade realizados

Critérios de aceitação:
- [x] Conter uma tabela em excel para registro

**Comment by inddiara** [comment]
https://docs.google.com/spreadsheets/d/1sFCJr69_lTcMED92uhZMPL1u5priGWfn81ZjPXNGohE/htmlview# esse modelo de resultados foi escolhido para documentar os resultados em uma tabela
