### ISSUE TITLE
US02: Eu como usuário desejo que o sistema obtenha a latitute e a logitude de qualquer lugar do mundo a partir da API do Google Maps

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#24]
US02: Eu como usuário desejo que o sistema obtenha a latitude e a longitude de qualquer lugar do mundo a partir da API do Google Maps

Nessa issue será realizado:
- [x] Criar classe que faz requisição na API
- [x] Exibir resultado no localhost
- [x] Aplicar testes unitários

Critérios de aceitação:
- [x] Fazer requisição na API
- [x] Estar testado
- [x] Exibir no localhost
- [ ] Receber o nome de local através da requisição
- [ ] Salvar dados da requisição no banco

**Comment by AmandaMuniz** [comment]
Então, EPS descobriu que a API do Google Maps é paga. A opção encontrada para ser substituta é a [OpenCage Geocoder](https://opencagedata.com/). Ela tem limitação de 2500 requests por dia e dá uma lista de resultados com a latitude e longitude da palavra pesquisada, por isso, a resposta dela deve ser tratada. Para essa US esse tratamento não precisará ser feito, só peguem o primeiro item da lista para a requisição. E usem essa API, por favor. Mandarei a API Key pelo Telegram.

**Comment by micaellagouveia** [comment]
Nós ja compramos a API do Google Maps, mas não pagamos nada, pois temos um crédito de 300 dólares por mês, e cada requisição vale 0.25 de dólar.
