### ISSUE TITLE
Construir um chatbot individual para estudo

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#25]
Construir um chatbot individual para estudo

Nessa issue será realizado:
- [x] Bot individual Eduardo
- [x] Bot individual Luís
- [x] Bot individual Micaella
- [x] Bot individual Samuel
- [x] Bot individual Sofia

Critérios de aceitação:
- [x] Estar no github pessoal de cada um
- [ ] Inclusão de um readme breve explicando o que o bot faz

**Comment by sofiapatrocinio** [comment]
Repositório chatbot: https://github.com/sofiapatrocinio/chatbot

**Comment by micaellagouveia** [comment]
Repositório chatbot: https://github.com/micaellagouveia/simplechatbot

**Comment by SamButers** [comment]
Repositório do Chatbot: https://github.com/SamButers/Le-Chat

**Comment by Ed-vL** [comment]
Repositório do Chatbot: https://github.com/Ed-vL/Luna

**Comment by Ed-vL** [comment]
Repositório Chatbot do Luís: https://github.com/LhTaira/RasaBot
