### ISSUE TITLE
Consertar a gaia no facebook 

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#253]
### Consertar a gaia no facebook 

Nessa issue será realizado:
- [x] Adicionar pages_messaging
- [x] Enviar vídeo de funcionalidade para análise

Critérios de aceitação:
- [x] Adequar às políticas exigidas no facebook

**Comment by sofiapatrocinio** [comment]
Enviei hoje, para o Facebook, um vídeo para análise, gravado pelo Calebe, explicando o que é Gaia, sua funcionalidade e como o uso da permissão `pages_messaging` não afetará os termos do Facebook. Esta função permite que a aplicação envie e receba mensagens usando uma Página do Facebook para qualquer usuário e não só desenvolvedores.
