### ISSUE TITLE
Criar identidade visual da Gaia

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#26]
Criar Identidade Visual - personalidade + logo 

Nessa issue será realizado:
- [x] Criar personalidade
- [x] Criar a logo
- [x] Criar as falas

Critérios de aceitação:
- [x] Apresentação em slides (Google slides ou PowerPoint, etc)
- [x] Logo e descrição da personalidade documentados na wiki
- [x] Conformidade com a paleta de cores

**Comment by inddiara** [comment]
Para ajudar na definição de personalidade: https://medium.com/chatbots-dados-do-mercado-brasileiro/https-medium-com-o-marcelocastro-construa-a-emocao-humana-do-seu-bot-525caa504341
