### ISSUE TITLE
Configurar a folha de estilo nodeJS

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#28]
Configurar a folha de estilo nodeJS com eslint

Nessa issue será realizado:
- Configuração da folha de estilo do repositório do Clima
- Configuração da folha de estilo do repositório do Clima

Critérios de aceitação:
- [x] O arquivo de configuração do eslint estar em ambos os repositórios.

**Comment by CalebeRios** [comment]
Eu achei problemas para usar o eslint em desenvolvimento utilizando o docker. Como o docker sobe uma instância isolada, o editor não consegue ter acesso as dependências necessárias e não consegue fazer a verificação do código em tempo de desenvolvimento. Estou indo atrás de uma solução de conseguir rodar o eslint através do docker para pelo menos mostrar os erros e warnings.
