### ISSUE TITLE
Criar pipeline de implementação

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#31]
Criar pipeline de implementação

Nessa issue será realizado:
- [x] Listagem das tarefas que devem ser feitar em um fluxo de implementação.
- [x] Criação do processo com essas tarefas.

Critérios de aceitação:
- [x] Estar documentado na wiki
- [x] Estar com notação BPMN

**Comment by AmandaMuniz** [comment]
Quando criei o roadmap coloquei o nome errado para essa documentação. O certo é processo de implementação e ele vai ser um tópico do documento de arquitetura a partir da Sprint 4.
