### ISSUE TITLE
Daily Sprint 2 - 30/3 a 6/4

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#44]
Nessa issue estarão todas as dailies remotas da Sprint 2

**Comment by inddiara** [comment]
@lucianaribeiro Terminei meu roadmap, validei e evoluí a EAP com a prof e to iniciando o canvas

**Comment by AmandaMuniz** [comment]
@lucianaribeiro Hoje eu terminei os roadmaps que tinha começado ontem, criei a nova versão da arquitetura (com clima sem banco e a api trocada) e agora estou fazendo a pipeline de implementação

**Comment by lucianaribeiro** [comment]
@lucianaribeiro Eu arrumei as branches, subi a wiki pra master e fiz deploy. Pretendo terminar a documentação do resultado da sprint1 hoje e subir para a wiki o planejamento da sprint 2.

**Comment by Ed-vL** [comment]
@lucianaribeiro Arrumei o nome da branch no repositório de clima, commitei nela o código da requisição de API funcionando, faltando somente o teste unitário.

**Comment by LhTaira** [comment]
Ontem tentei ter ideias para definir a personalidade da Wendy mas falhei miseravelmente, então tentei começar meu bot de novo e novamente falhei miseravelmente. Hoje mica e Sofia vieram aqui pra casa, e estão aqui agora, e estamos fazendo a conexão com o banco. A conexão do banco só funcionou há alguns minutos atrás e estamos agora tentando colocar dados no banco.

**Comment by micaellagouveia** [comment]
Comecei a fazer o meu bot, mas estou tendo problema pra treina-lo. 
Estou com o Luis e a Sofia tentando inserir dados no banco, hj já conseguimos fazer a conexão, e provavelmente mais tarde pesquisarei sobre a persona e testes

**Comment by SamButers** [comment]
De ontem pra hoje, eu e o Eduardo já começamos a nossa issue da Story User 01 e estamos no momento tentando implementar os testes.
Também consertei o sumário do documento de visão o qual estava com problemas até então não previstos no docsify.
E por último, também consegui instalar o que tinha que instalar do Rasa no Linux, que estava tendo problemas antes, embora minha máquina ainda não consegue rodar o Tensorflow por falta de AVX, o que dificulta eu consertar o meu querido bot. Estou me aventurando atrás de um package do Tensorflow sem AVX, para Python 3.x e da versão 1.12.0.

**Comment by sofiapatrocinio** [comment]
Hoje comecei a estudar sobre nossa identidade visual, mas o foco foi banco de dados, arrumamos o mongoose e agora estou tentando colocar dados da aṕi no banco

**Comment by CalebeRios** [comment]
@lucianaribeiro Eu terminei a integração continua de um microsserviço, mas falta de uma ainda. Além disso falta fazer o Docker de rasa para a próxima sprint
