### ISSUE TITLE
Conseguir autenticação com mongoose

### ISSUE THREAD

**Issue by sofiapatrocinio** [fga-eps-mds/2019.1-Gaia#45]
Já construí o esquema do mongoose, porém está dando falha na autenticação. Quando peço para retornar o erro pro console aparece a seguinte mensagem: 'command insert requires authentication', code: 13, codeName: 'Unauthorized ', name: 'MongoError'. É necessário passar alguma função admin?

![dbfdd74f-accf-40b5-96e3-fb66476ae24b](https://user-images.githubusercontent.com/38709421/55594260-49775d80-5715-11e9-90c9-83e48a242db5.jpg)

**Comment by CalebeRios** [comment]
O mongo pede uma configuração do database e do usuário. Eu alterei o a imagem do docker que estavamos utilizando para o mongo, e alterei algumas configurações do moongose. A alteração necessária está nesse commit [b35a422915c5a2ae8f48a6d3a5105a8c0565e790](https://github.com/wendybot/Wendy-Local/commit/b35a422915c5a2ae8f48a6d3a5105a8c0565e790)

**Comment by CalebeRios** [comment]
@sofiapatrocinio, irei fechar a issue, mas se tiver dúvidas pode reabrir.

**Comment by CalebeRios** [comment]
Só salvando o git de onde se encontra a imagem do mongo que estamos utilizando: https://github.com/aashreys/docker-mongo-auth
