### ISSUE TITLE
US05: Eu como usuário desejo que a API Clima chame a API Local para que o sistema possa receber o clima do local

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#65]
US05: Eu como usuário desejo que a API Clima chame a API Local para que o sistema possa receber o clima do local

Nessa issue será realizado:
- [x] Interagir Busca Clima com Busca Local
- [x] Busca Clima requerir da Busca Local a latitude e longitude
- [x] Exibir no localhost a requisição feita pelo Busca Clima

Critérios de aceitação:
- [ ] Eslint sem erros e warnings
- [ ] Estar testado
- [ ] Inserir qualquer local e obter o clima respectivo a ele
- [ ] Exibir no localhost

**Comment by inddiara** [comment]
> US05: Eu como usuário desejo que a API Clima chame a API Local para que o sistema possa receber o clima do local
> 
> Nessa issue será realizado:
> 
> * [ ]  tarefa 1
> * [ ]  tarefa 2
> * [ ]  tarefa 3
> 
> Critérios de aceitação:
> 
> * [ ]  Eslint sem erros e warnings
> * [ ]  Estar testado
> * [ ]  Inserir qualquer local e obter o clima respectivo a ele
> * [ ]  Exibir no localhost

**Comment by SamButers** [comment]
Fizemos a Pull Request no repositório Gaia-Clima.
Quatro dos cinco testes falharam e fica aqui algumas observações do que se teoriza poder ser a causa de tais:
- O docker do Clima necessita se comunicar com o do Local para adquirir as latitudes e longitudes;
- Foi adicionado um novo parâmetro ao docker run do Clima.

Estamos na espera do feedback para saber o que pode estar causando os erros.

**Comment by CalebeRios** [comment]
@SamButers Boa noite, para rodar os testes, os projetos não podem ser dependentes. O teste unitário testa somente a função do projeto onde ele se encontra. Como tem uma dependencia assim, eu recomendo que simulem a resposta do outro projeto. Ficou claro?

**Comment by SamButers** [comment]
Agradeço a ágil resposta.
Creio que não compreendi o que quer dizer com simular a resposta do outro projeto.

**Comment by CalebeRios** [comment]
@SamButers Está quebrando porque vocês fizeram a requisição de um serviço que para o Travis não existe. Mas vocês não querem testar se a requisição desse serviço que não “existe” funciona, pois ele já tem seu próprio teste. Então vocês podem passar na mão como seriam o resultado dele. Entendeu?

**Comment by SamButers** [comment]
@CalebeRios Compreendi o que quer dizer, mas não compreendo como poderíamos passar na mão como seria o resultado dessa requisição para os testes do Travis.

**Comment by CalebeRios** [comment]
@SamButers Não precisa passar isso para os testes do Travis, e sim para o teste mesmo. Melhor forma para você testar esse caso, é não subir o Docker do outro serviço
