### ISSUE TITLE
Planejamento das Reuniões da Sprint

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#8]
O objetivo dessa issue é manter a rastreabilidade de todas as reuniões semanais, assim como o planejamento da reunião da próxima sprint.

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 30/03/2019] - *Sprint 2* 

### Review: O que foi feito durante a *Sprint 1* - 1h35 min
#### MDS
- [x] Documento de Visão - 10 min
- [ ] Documento de Arquitetura - 10 min
#### EPS
- [x] Guia de Contribuição - 10 min
- [x] Docker dos microserviços - 40
- [x] TAP - 5 min
- [x] EAP - 5 min
- [x] Licença - 5 min

### *Retrospective*: Aprendizados obtidos na *Sprint 1* - 30 min
   - Eduardo: Ficou perdido sobre o que tinha que estudar e saiu estudando muito. Interessante aprender sobre toda a burocracia de abrir um projeto open source. Doc de Arquitetura com prazo apertado. 
   - Luis: Tentou aprender Raza. Não gostou do prazo do Doc de Arquitetura. Boa comunicação do time. Todos fazem as coisas bem feito, e não precisa ficar pegando no pé. 
   - Sofia: Ainda um pouco confusa sobre o back. Procurou o Blanco para explicar sobre a estrutura do chatbot e como sincronizar com Facebook e Telegram. Preocupada com o prazo de entrega.
   - Micaella: Focou em Raza mas nao conseguiu fazer muita coisa. Está animada com a API e apreensiva com o projeto por causa das provas. Não conseguiu estudar JavaScript e se organizar direito nos estudos, focou mais em Rasa.
   - Samuel: Estudou Python mas não aprendeu tanto quando gostaria. Prazo do Doc de Arquitetura curto.   
   - Amanda: Curva de aprendizagem em arquitetura surreal. Conversou com a professora Milene sobre a arquitetura do projeto. Sentiu que aprendeu muito. 
   - Indiara: Gostou da sprint mas estava muito perdida.  Já sabe o que tem que fazer na primeira parte do projeto. O tempo é apertado mas conseguiu entregar o que tinha para entregar, gosta da forma como o time trabalha. 
   - Calebe: A sprint foi corrida, estava perdido no início da semana mas conseguiu entregar o principal. O Docker foi legal de mexer. Preocupado com a prox Sprint pq tem integração continua. 
   - Luciana: Estava perdida no começo da Sprint, pediu ajuda para muitas pessoas e teve êxito, complicado ser Tec Lider, tem que guiar todos. Mas conseguiu se direcionar bem, gostou da sprint e teve uma curva de aprendizagem alta, acha que o está caminhando bem, todos unidos. 


### *Planning*: Planejamento da *Sprint 2* - 1h 


#### MDS
* US01: Eu como usuário desejo que o sistema obtenha  o clima de uma cidade para que eu possa saber as condições climáticas do dia - Eduardo e Samuel [8]
* US02: Eu como usuário desejo que o sistema obtenha a latitute e a logitude de qualquer lugar do mundo a partir da API do Google Maps. - Luís, Micaella e Sofia [13]
* Construir um chatbot individual para estudo - Todos [5]
* Identidade Visual - personalidade + logo - Luís, Micaella e Sofia [3]
* Protótipo de baixa fidelidade - Eduardo e Samuel [5]

#### EPS
* Configurar a folha de estilo nodeJS - Calebe [3]
* Integração contínua de cada repo (2 issues) - Calebe [8]
* Pipeline de implementação - Amanda[3]
* Elicitar requisitos - Todos [13]
* Criar readme - Luciana [1]
* Plano de métricas / Produtividade (horas) / Conhecimento - Luciana [5]
* Plano de metodologia - Luciana [3]
* Documentação da Sprint  - Luciana [1]
* Adicionar critérios de aceitação das issues - Indiara [3]
* Canvas - Indiara [5]



 

## Observações levantadas ao longo da reunião:

- Todos os membros de MDS participaram da construção direta de pelo menos um item. 
- O documento de arquitetura não foi finalizado 
- Amanda apresentou para MDS como funcionará a arquitetura do projeto
- Calebe tem que passar as versões das tecnologias
- O guia de identidade visual será dividida entre MDS e Tech Lead. MDS serão responsáveis pela personalidade do bot. Tech Lead pelos outros tópicos.

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 6/04/2019] - *Sprint 3* 

### Review: O que foi feito durante a *Sprint 2* - 1h30
#### MDS
* Identidade Visual
* Protótipo de baixa fidelidade 
* Code Review das US01 e US02

#### EPS
* TAP
* EAP
* Canvas
* Resultado da Sprint 1
* Plano de metodologia
* Plano de métricas

### *Retrospective*: Aprendizados obtidos na *Sprint 2*
#### Health Check

| - | Pontuação |
| --------- | -------- |
| Trabalho em Equipe  | 2 |
| Velocidade  | 1 |
| Respeito  | 3 |
| Propósito  | 1 |
| Aprendizado  | 1 |
| Diversão  | 2 |
| Empoderamento  | 1 |
| Facilidade de Equipe  | 2 |
| Saúde do Código  | 2 |


### Pontos Positivos
- Muitas perguntas de dúvidas
- Comunicação e transparência com EPS
- Grande esforço de todos  
- Todos receberam ajudas e todos estavam dispostos a ajudar
-  DevOps e Arquiteta comprometidos e ajudando o grupo de MDS
- Integração com a equipe
- Souberam delegar tarefas
- Mais atividas práticas
- Aprenderam mais sobre os colegas e como eles trabalham 
- Compromisso com os rituais
- Pull Request escritos de forma bonitinha

### Pontos negativos
- Muitas tarefas
- Desorganização da equipe 
- Perdidos no que tinha que fazer
- Pouca comunicação com o outro time de MDS

### Pontos a Melhorar 
- Não abrir PR sexta ou sabado de manhã
- Entregar mais rápido
- Mover os cards
- Menos pontuações na sprint
- Desorganização
- Critérios de aceitação
- Melhorar a comunicação nas issues


### *Planning*: Planejamento da *Sprint 3* 


#### MDS

* US03: Eu como usuário desejo interagir com a Gaia para que ela me responda. [13]
* US04: Eu como usuário desejo que o sistema salve os locais com suas latitudes e longitudes para que o sistema não precise fazer diversas requisições.[8]
* US05: Eu como usuário desejo que a API Clima chame a API Local para que o sistema possa receber o clima do local. [5]

#### EPS

* Padrões de software [8]
* Integração de microserviços [8]
* Integração contínua da gaia [8]
* Priorizar backlog [5]
* Refinar os requisitos em US e tasks [13]
*  Organizar o backlog [3]
* Definir conselheiro [8]
* Análise de riscos [5]
* Métricas de produtividade [5]
* Documentar planejamento da sprint 3 [1]
* Documentar resultados da sprint 2 [3]
* Guia de comunicação [3]
* Treinamento de testes [5]

Total de pontos: 135
Pontos de dívida: 34


## Observações

* Tratamento de dados, como tradução para português, unidades de medida e etc.
* Gerar cobertura de testes

## Backlog de melhoria 
* Identidade visual 
* Dados do clima 

### Pareamentos:

Luís, Samuel e Eduardo
Eduardo e Sofia

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 13/04/2019] - *Sprint 4* 

### Review: O que foi feito durante a *Sprint 3* - 30
#### MDS
* Code Review da US03
* Optamos por terminar as histórias que ficaram de dívida técnica na Sprint 3  

### *Retrospective*: Aprendizados obtidos na *Sprint 3*
#### Health Check

| - | Pontuação |
| --------- | -------- |
| Valor de Entrega | 2 |
| Trabalho em Equipe  | 2 |
| Velocidade  | 1 |
| Respeito  | 2 |
| Propósito  | 3 |
| Aprendizado  | 3 |
| Diversão  | 1 |
| Empoderamento  | 3 |
| Facilidade de Equipe  | 1 |
| Saúde do Código  | 2 |

* Imagem da dinâmica de retrospectiva 

### *Planning*: Planejamento da *Sprint 3* 

#### MDS
* Continuar as dívidas técnicas 
* US06: Eu como usuário desejo obter resposta plausíveis sempre que eu falar com a Gaia para que eu possa manter um diálogo [3]
* US07: Eu como usuário desejo que o sistema seja capaz de tratar os dados referentes ao clima para que eu possa entende-los. [5]

#### EPS

* Evoluir documento de arquitetura [1]
* Deploy Gaia homolog [5]
* Deploy Local homolog [3]
* Deploy Clima homolog [3]
* Passar toda a integração contínua para o gitlab-ci [3]
* Definir parâmetros para as modalidades [5]
* Evoluir documento de visão e protótipos [1]
* Planejar Sprint 4 [1]
* Documentar resultados da Sprint 3 [3]
* Evoluir plano de métricas [1]


Pontos planejados: 34
Pontos de dívida: 31
Total de pontos: 65

## Observações

* Foi reduzida a quantidade de tarefas de EPS, levando em conta que as entregas estavam sendo prejudicadas, principalmente pelo tempo usado para ajudar MDS.


## Backlog de melhoria 
*  Adicionar endpoints no index e mostrar no localhost

### Pareamentos:
sofia e mica - rasa + tratamento do clima
samuel, luis e edu - dividas

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 20/04/2019] - *Sprint 5* 

### Review: O que foi feito durante a *Sprint 4* 
#### MDS
* Code review: US04, US05, US06 e US07

#### EPS
* Diagrama de classe
* Rancher
* Plano de riscos e resultados da sprint passada
* Protótipo de alta fidelidade
* Evolução do documento de visão

### *Retrospective*: Aprendizados obtidos na *Sprint 4*
#### Health Check


### Pontos Positivos
Bom planejamento de MDS
Bons pareamentos
Independência no que precisava fazer
Objetivos mais claros do que precisava ser feito
Adequação da arquitetura antes que MDS fizesse a parte mais complexa da aplicação
MDS está escutando mais a arquiteta e o DevOps


### Pontos negativos
Compromisso com os rituais
Problemas inesperados com Docker
MDS faltando aula de MDS pra codar


### Pontos a Melhorar 
Pouca comunicação entre os times de MDS
Mover os cards
Melhorar a comunicação nas issues
Houve uma queda em tirar dúvidas com EPS


### *Planning*: Planejamento da *Sprint 5* 


#### MDS

##### US08 - Eu como usuário desejo que a Gaia me responda de forma coerente [3] - Sofia e Eduardo
1. Diminuir o tamanho dos textos de resposta
2. Apresentar as funcionalidades do bot
3. Definir fluxo principal
4. Seguir fluxo principal de conversa

##### US09 - Eu como usuário desejo que a Gaia forneça os dados corretos a respeito de clima [13] - Sofia e Eduardo
1. Adicionar slots nas entidades 
2. Tratar slots
3. Configurar uma custom action genérica na Gaia
4. Transformar custom action genérica em específica

##### US10 - Eu como usuário desejo que a Gaia forneça os dados corretos a respeito do esporte [5] - Sofia e Eduardo
1. Criar fake JSON com os esportes
2. Adicionar slots nas entidades
3. Tratar slots
4. Configurar uma custom action genérica na Gaia
5. Transformar custom action genérica em específica

##### US11 - Eu como usuário desejo que o sistema consiga filtrar o esporte de acordo com as condições meteorológicas [8] - Micaella e Luís
1. Fazer conexão com o MongoDB
2. Criar schema e a model
3. Fazer a task para salvar os esportes no banco
4. Comparar o esporte com o clima atual
5. Retornar para o usuário os esportes  

##### US12 - Eu como usuário desejo que o sistema retorne o local com mais acurácia e precisão [13] - Calebe e Samuel

1. Pensar numa forma de tratamento 
2. Inserir as tasks seguintes quando decidirem como fazer


#### EPS

* Viabilidade ténica de cada frente
1. Arquiteta: Justificativa da definição da arquitetura [3] e procurar referencias externas 
2. DevOps: Documentação da folha de estilo[3], pipeline[3] e procurar referencias externas
3. Product Owner: Oceano Azul[3] e procurar referencias externas
4. Tech Lead: procurar referencias externas

* Estudo da parte de composição da API Gateway - Amanda [5]
* Evoluir os diagramas de classe e pacote [1]
* Alterar o Docker para aceitar esporte - Calebe [3]
* Criar repositório da API Gateway - Calebe [1]
* Deploy de esporte em homolog - Calebe [3]
* Enriquecer a tabela de esportes - Indiara [1]
* Documentar técnicas de requisitos - Indiara [3]
* Criar roadmap geral - Luciana [5]
* Documentar planning da sprint 5 - Luciana [1]
* Documentar resultados da sprint 4 - Luciana [3]

Total de pontos: 80
Pontos de dívida: 5

## Backlog de melhoria 
##### US13 - Eu como usuário desejo que o serviço me indique os endpoints [1]
1. Adicionar endpoints da Gaia Clima no index
2. Adicionar endpoints da Gaia Local no index

### Pareamentos:

1. Micaella e Luís
2. Sofia e Eduardo
3. Calebe e Samuel

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 27/04/2019] - *Sprint 6* 

### Review: O que foi feito durante a *Sprint 5* 
#### MDS
* Code review: US08, US09, US10, US11, US12


### *Retrospective*: Aprendizados obtidos na *Sprint 5*
#### Health Check

### Pontos Positivos
* Time de MDS trabalhou como um time integrado
* Aplicar na pratica o que aprendeu na teoria 
* Time de MDS mais maduro 

### Pontos negativos
* Sprint muito pesada
* O produto nao tem cara de produto ainda
* Muitas atividades para eps surgiram no final da sprint
* A arquitetura foi mudada de última hora
* E problema com api externa

### Pontos a Melhorar 
* Formas melhores de compartilhar conhecimento 
* Rever a forma como os pareamentos sao feitos 

### *Planning*: Planejamento da *Sprint 6* 


#### MDS

* Eu como usuario desejo que a gaia consiga guardar meus dados e minhas preferencias [8] - Eduardo e Micaella 
* Eu como usuario desejo que a gaia me informe se um determinado esporte eh favoravel de ser realizado ou nao [5] - Samuel, Sofia e Luis

#### EPS

* issue [pts]
* issue [pts]
* issue [pts]


Total de pontos: pts
Pontos de dívida: pts

## Backlog de melhoria 
* Criar issue de melhoria na interacao da gaia 

### Pareamentos:

1. Eduardo e Micaella
2. Sofia, Samuel e Luis

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 04/05/2019] - *Sprint 7* 

### Review: O que foi feito durante a *Sprint 6* 
#### MDS
* Code review: US14, US15

### *Retrospective*: Aprendizados obtidos na *Sprint 6*

### Pontos
#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)

### Pontos Positivos
* Melhor difusão de conhecimento
* Volume de trabalho de MDS, pois eles puderam se dedicar a outras matérias 
* Bons pareamentos
* Release 1
* MDS integrado e trabalhando em equipe.

### Pontos negativos
* Cansaço por conta da Release 1
* Pouco tempo de dedicação para o projeto
* A velocidade de entregas está muito devagar
* Pouca coisa aprendida
* R1 deixou os integrantes dispersos o restante da sprint

### Pontos a Melhorar 
* Velocidade de entrega  
* Levar a sério o backlog de melhoria. 
* Melhorar conversa da Gaia.
* Organizar melhor quando vão ocorrer os pareamentos

### *Planning*: Planejamento da *Sprint 7* 

#### MDS

* US 16 - Eu como usuário desejo agendar uma notificação[5] - Sofia, Micaella e Luís
* US17 - Eu como usuário desejo que o sistema consiga a previsão de até cinco dias[3] - Samuel e Eduardo
* US18 - Eu como usuário desejo que o sistema Gateway seja capaz de gerenciar minhas requisições de esporte[5] - Samuel e Eduardo
* US19 -Eu como usuário desejo que a Gaia me responda com mais acurácia e precisão[3] - Sofia, Micaella e Luís

#### EPS

* Definir microsserviço do ciclone [5]
* Criar EVM [5]
* Adicionar cobertura de testes dos microsserviço [1]
* Configurar deploy contínuo [3] 
* Documentar planejamento da Sprint 7 [1]
* Documentar resultados da Sprint 6 [3]

Total de pontos: pts
Pontos de dívida: pts

## Backlog de melhoria 
* Melhorar conversa da Gaia

## Observações na reunião

Reunião feita em duas partes para que todos os integrantes de MDS pudessem participar. Sem três integrantes de EPS. 
### Pareamentos:

1. Samuel e Eduardo
2. Sofia, Micaella e Luís

**Comment by AmandaMuniz** [comment]
perguntar para o usuario a preferencia de notificacao dele

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 11/05/2019] - *Sprint 8* 

### Review: O que foi feito durante a *Sprint 7* 
#### MDS
* Code review: 

### *Retrospective*: Aprendizados obtidos na *Sprint 7*

### Pontos
#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)

### Pontos Positivos
* Foi interessante trabalhar com coisas novas
* Time de MDS  trabalhando bem em equipe 
* Integração boa entre toda a equipe, boa comunicação  
* Comunicação das issues
* Backlog de melhoria

### Pontos negativos
* Ritmo quebrado
* Divida técnica atrasada
* Sem metas definidas para a sprint
* EPS cansado com os pepéis

### Pontos a Melhorar 
* Velocidade de entrega
* Motivação
* Falta de comprometimento ao aceitar PR de EPS
* Dívidas técnicas toda sprint
* Escopo mais desafiador


### *Planning*: Planejamento da *Sprint 8* 

#### MDS

#### US20: Eu como usuário desejo ver mais opções de local caso a minha não esteja não lista [5] - Sofia
* Fazer tratamento dos dados
* Apresentar as opções por botões

#### US21: Eu como usuário desejo que o sistema trate das opções de local repetidas [3]- Samuel
* tratar as mesmas cidades ou coordenadas próximas

#### US22: Eu como usuário desejo  saber a previsão do tempo de um determinado horário ou local de no máximo 5 dias.[5] - Luís

#### US23: Eu como usuário desejo que o sistema me notifique quando eu desejar[8] - Eduardo


#### EPS
* Verificar a viabilidade de saber se a cidade é litorânea ou não
* Teste de usabilidade 

Total de pontos: pts
Pontos de dívida: pts

## Backlog de melhoria 
* Melhorar conversa da Gaia
* Fazer o tratamento do fuso horário para brasília 
* Arrumar quando o usuário entra com apenas o nome do local 
* Melhorar interação inicial da Gaia

## Observações na reunião

### Pareamentos:

1. Cada membro ficou com 1 issue.

## Novas Issues levantadas ao longo da reunião:

#### US24: Eu como usuário desejo manter minhas notificações 

#### US25: Eu como usuário desejo que o Gateway trate minhas requisições

#### US26: Eu como usuário desejo que o Gateway autentique minhas requisições

#### US27: Eu como usuário desejo que o Notifica verifique se eu sou um usuário autentico.   

#### US28: Eu como usuário desejo que o sistema teste as requisições da Gaia.

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 18/05/2019] - *Sprint 9* 

### Review: O que foi feito durante a *Sprint 8* 
#### MDS
* Code review: US20, US21, US22, US23, 

### *Retrospective*: Aprendizados obtidos na *Sprint 8*

#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)

### Pontos Positivos
* Poder organizar sua propria rotina.
* Trabalho em equipe.
* Comunicacao entre EPS e MDS.
* Comunicacao nas issues e PRs.
* Backlog de melhoria.
* Muitos PRs abretos antes de sexta.


### Pontos negativos
* Falha na comunicacao de MDS
* Tarefas demoram a ser feitas sem pareamento
* Ritmo desacelerado
* Divida técnica atrasada

### Pontos a Melhorar 
* Motivacao
* Conversacao da Gaia
* Historia muito grande



### *Planning*: Planejamento da *Sprint 8* 

#### MDS

#### US24: Eu como usuário desejo que o Gateway trate minhas requisições
#### US25: Eu como usuário desejo que o Gateway autentique minhas requisições
#### US26: Eu como usuário desejo que o Notifica verifique se eu sou um usuário autentico.

#### EPS

#### Refatorar arquitetura
#### Criar e configurar novo repositorio
#### Refatorar os Gitlab CIs
#### Estudar deploy para facebook messenger
#### Estudar como coletar metricas do bot

Total de pontos: pts
Pontos de dívida: pts

## Backlog de melhoria 
* Passar Gaia-Local para Gaia-Esporte - 19/5
* Passar Gaia-Clima para Gaia-Esporte - 21/5
* Passar Gaia-Notifica para Gaia-Esporte - 25/5

## Observações na reunião
* Mudar foco da Gaia para esporte

### Pareamentos:

1. Luis e Eduardo - Histórias
2. Sofia, Samuel e Micaella - Backlog de Melhoria

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 25/05/2019] - *Sprint 10* 

### Review: O que foi feito durante a *Sprint 9* 
#### MDS
* Code review:  MDS contou sobre o que cada um fez, dificuldades e pq não entregaram 

### *Retrospective*: Aprendizados obtidos na *Sprint 9*

#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)

### Pontos Positivos

### Pontos negativos
* MDS teve pouco tempo para se dedicar ao projeto

### Pontos a Melhorar 
* Falhas de comunicação de MDS com EPS 


### *Planning*: Planejamento da *Sprint 10* 

#### MDS

#### EPS


## Backlog de melhoria 
## Observações na reunião
* Criar issue para passar as requisições para axios do gateway

### Pareamentos:

1. 
2.

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 01/06/2019] - *Sprint 11* 

### Review: O que foi feito durante a *Sprint 10* 
#### MDS
* Code review: MDS contou sobre o que cada um fez, dificuldades e pq não entregaram


### *Retrospective*: Aprendizados obtidos na *Sprint 10*

#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)

### Pontos Positivos
* Feedback dado na reunião passada deu um gás pra galera
* Boas equipes de pareamento
* MDS preocupado com o produto
* MDS proativo resolvendo as próprias issues
* Cobertura de testes top

### Pontos Negativos
* Dificuldade de terminar as issues a tempo devido ao pouco tempo (começaram na terça por causa das dívidas técnicas)
* O time terá que lidar com a API de ciclone que só faz 750 requisições por conta
* Reunião por hangouts 
* reuniões estão sendo muito longe pra algumas pessoas 

### Pontos a Melhorar 
* Uma equipe de pareamento teve que resolver muita coisa que não tava funcionando 


### *Planning*: Planejamento da *Sprint 11* 

#### MDS
* US25: Eu como usuário desejo que o Gateway autentique minhas requisições - Samuel
* US26: Eu como usuário desejo que o sistema faça uma nova requisição a cada 2 horas - Eduardo e Luís
* US28: Eu como usuário desejo manter minhas notificações de ciclone - Micaella e Sofia

#### EPS
* Estudar testes de integração - Amanda
* Documentar os resultados do teste de usabilidade - Indiara

## Backlog de melhoria 
## Observações na reunião
* Essa reunião foi realizada por hangouts
### Pareamentos:

1. Eduardo e Samuel 
2. Micaella e Sofia
3. Samuel

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 08/06/2019] - *Sprint 12* 

### Review: O que foi feito durante a *Sprint 11* 
#### MDS
* Code review: MDS contou sobre o que cada um fez e as dificuldades.

#### Dívidas da Sprint 11
* Configurar o Kibana com Elasticsearch
* Estudar testes de integração
* Criar EVM 
* Documentar os resultados do teste de usabilidade


### *Retrospective*: Aprendizados obtidos na *Sprint 11*

#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)


### Pontos Positivos
* Não tiveram dívidas de MDS
* Escopo fechado
* Boas duplas de pareamento
* Mais PRs abertos
* Proatividade para corrigir Bugs 

### Pontos Negativos
* EPS precisará codar o Gateway
* PO, DevOps e Arquiteta não entregaram na sprint

### Pontos a Melhorar 
* Melhorar conversação da Gaia
* Horário do começo da reunião
* Atraso de alguns membros
* Faltas na daily

### *Planning*: Planejamento da *Sprint 12* 

#### MDS
* Eu como usuário desejo ser notificado quando tiver um ciclone no mundo - Samuel
* Melhorar fluxo de conversa de esporte - Micaella, Eduardo e Luís
* Melhorar fluxo de conversa de ciclone - Sofia

#### EPS
* Refatorar o gateway - backlog de melhoria
* Verificar o procedimento para subir a gaia no facebook - Sofia e Indi

## Backlog de melhoria 

## Observações na reunião

### Pareamentos:

1. 
2. 
3.

**Comment by lucianaribeiro** [comment]
## [PLANEJAMENTO - 08/06/2019] - *Sprint 13* 

### Review: O que foi feito durante a *Sprint 12* 
#### MDS
* Code review: MDS contou sobre o que cada um fez e as dificuldades.

#### Dívidas da Sprint 12
* Criar README do Ciclone
* Criar EVM

### *Retrospective*: Aprendizados obtidos na *Sprint 12*

#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)


### Pontos Positivos
* Não tiveram dívidas de MDS
* EPS deixou poucas dívidas
* MDS puxando daily
* Todos de MDS abrindo e resolver issue de bug
* Trabalho em equipe
* Escopo fechado

### Pontos Negativos
* Nao abriram pequenos PRs ao longo da sprint
* EPS não participou tanto das dailies

### Pontos a Melhorar 
* Horário do começo da reunião
* Atraso de alguns membros
* Faltas na daily


### *Planning*: Planejamento da *Sprint 12* 

#### MDS
* Consertar a notificação - Luís 
* Adicionar novos esportes - Eduardo
* Melhorar a conversa da gaia - Micaella
* Consertar a gaia no facebook - Sofia
* Melhorar a cobertura de testes - Samuel

#### EPS

* Melhorar os READMEs - Calebe
* Refatorar os diagramas - Amanda
* Revisar todos os documentos - Luciana e Indiara
* Colocar todas as tarefas nas issues passadas de devops - Calebe
* Criar documentação da folha de estilo - Calebe
* Começar o post mortem - Todo o time de EPS
* Colocar critérios de aceitação em todas as issues passada - Indiara

Novos Riscos:
* A funcionalidade de notificação não funcionar

### Pareamentos:

1. 
2. 
3.

**Comment by lucianaribeiro** [comment]
## Reunião Final (22/06/2019)

### Review: O que foi feito durante a *Sprint 13* 

* Code review: Todos do time testaram a Gaia e foram levantando melhorias que devem ser feitas  

### *Retrospective*: Aprendizados obtidos na *Sprint 13*

#### Health Check (a tabela ta no drive)
#### Quadro de conhecimento (ta no drive)


### Percepção individual de cada um:

Eduardo: se tornou outra pessoa na parte de aluno de eng de soft. Sabe muito melhor como trabalhar em equipe em prol do projeto. Conhecimento técnico evoluiu exponencialmente, se sente capaz de fazer muitas coisas. Poder da amizade esteve muito presente, se aproximou dos amigos de mds e se aproximou dos veteranos incríveis (EPS). 

Luís: Essa matéria foi incrível de aprender tanto tecnicamente quanto socialmente, pq o conhecimento técnico é muito grande assim como o conhecimento de trabalho em grupo e relacionamento com pessoas. É muito bom para interagir com pessoas de outros semestres. Esse formado de tutores fez muita diferença na vida de mds. Se tornou outra pessoa por causa dessa matéria. Foi muito intenso. É uma fase do curso e da vida que é muito triste ir embora. 

Micaella: Sempre foi uma pessoa desesperada e tinha muito medo dessa matéria e ter pessoas tão boas, tanto de EPS quanto de MDS, acalmou o coração. Mesmo com o início conturbado, o apoio que EPS deu, trouxe muita confiança e viu que pode fazer muitas coisas que nunca achou que poderia fazer. Grande amadurecimento, nunca fez um trabalho tão intenso. Esse trabalho se tornou parte da nossa vida. Se tornou mais comprometida e mais confiante. Tinha muito medo de EPS porém a liderança de EPS foi muito importante e trouxe muita confiança e segurança. 

Samuel: Acredito que MDS foi uma experiência interessante que trouxe diversas contribuições ao aprendizado de diversas ferramentas, como no aprendizado na forma em que o trabalho em equipe ocorre. Também, como o Eduardo disse, acredito que tivemos ótimos membros de EPS, como também tivemos de MDS, o que fica evidente em nosso resultado.

Sofia: Como as pessoas se desenvolvem e se comportam de forma diferente em trabalho em grupo. Aprender o tempo de cada um, principalmente em MDS, e que cada um tem uma forma individual e aprender a. Eps fez um trabalho muto bom, inspiramos confiança e foi essencial . Coloram desafios e demos apoio para resolverem. Queria fazer MDS todo semestre e se sente preparada para qualquer problema. 

Calebe: As vezes EPS nem sabe o que ta fazendo, porém temos que correr atrás e um dos maiores aprendizados é que nao importa o que ta rolando, ninguem nunca sabe tudo, seja com o google ou com outras pessoas, sempre vamos precisar de ajudar e sempre vai ter alguém que sabe mais do que a gente. EPS foi uma matéria muito legal de fazer, porém muito pesada. Trouxe uma rotina de fazer um pouco a cada dia. Aprendeu a se organizar bem pouquinho. Ficou bem feliz primeiro com EPS pq cada um fez o que deveria fazer muito bem, cada um confiou muito no trabalho um do outro. Hoje não tem problema em passar atividade para qualquer um MDS, por estarem todos nivelados. Sabem como ir atrás e como procurar. Vão ser muito bons EPS.

Amanda: EPS pra mim foi desafiador, pq a ideia de que "o que eu falar" será levado com verdade absoluta e foi amedrontador. Ao mesmo tempo viu todos crescendo e deu muito orgulho, viu as pessoas realmente descobrindo o que gostam e se divertindo na matéria. Acho que pessoalmente EPS confirmou o TCC que quer fazer. Sente orgulho de EPS e de MDS por ver as pessoas que codavam no index.js crescer muito. Cumprimos nosso objetivo de ser EPS melhores do que EPS que nós tivemos e que MDS fosse muito melhor que nós fomos quando éramos MDS.   

Indiara: Antes de fazer a disciplina, tinha criado na cabeça que EPS era a matéria que você se matava e no final só tinha morrido, porém não entregava nada que seria usado. Descobriu paixões que nem imaginava que gostava. A motivação por EPS é o contato por coisas novas que se identificasse, foi muito legal ver a resposta do time com relação a isso. EPS confiando e se mostrando vulneráveis em algumas situações. No começo do projeto tinha muito medo da Amanda, porém com ela nao tinha muita intimidade e com medo de julgar pelos possíveis erros, porém foi muito pelo contrário, sempre estava la quando precisava. MDS progrediu em muito pouco tempo, acabaram de sair de OO e puxam o trabalho pra si e executam sem que haja distinção entre MDS e EPS. As queixas dos outros grupos não condiziam com a realidade do nosso grupo. É interessante ver como cada um crescer, a admiração pela Sofia pela pegada de dev e PO. Micaella cresceu muito, tem os pés no chão, pega e faz sem medo de errar, emponderada. Eduardo é o amuleto, sempre com a calmaria e a paciência, o equilíbrio do time, super maduro. Luís teimoso porém progrediu muito, escuta e sabe colocar as palavras. Samuel sempre polêmico por nao gostar de trabalhar em equipe, hoje tem conhecimento técnico muito bom e ao longo do tempo teve mais amadurecimento e tem mais tato pra lidar com as pessoas. 

Luciana: Quando a gente começou EPS/MDS, eu estava sem querer fazer a matéria, porque pensava que ia dar muito trabalho. No começo ficamos muito preocupados  com o Samuel, porque ele não entrava no Telegram. Pensamos logo "esse dai vai dar trabalho", só que foi exatamente o contrário, nossos problemas foram pequenos. Com vocês eu aprendi a ser paciente, a como dar feedback, a entender quando uma pessoa não tá bem e precisa de um tempo. Ao longo do tempo  equipe amadureceu muito em muitos pontos. Ver o quanto vocês cresceram e o quanto vocês realmente são muito melhores do que fomos. Quando MDS deixou de entregar nunca foi por falta de trabalho, era sempre um motivo maior. Eu estou orgulhosa porque todos vocês levaram o projeto a sério. Hoje se olharem nossas métricas, elas estão melhores. Eu confio em todo mundo de EPS de olhos fechados. Sendo bem sincera, só chegamos até aqui bem do jeito que chegamos, porque temos uma time de EPS maravilhoso. Eu só tenho a agradecer e não tenho queixa nenhuma. Não vou falar individualmente, mas é isso, o nosso resultado expressa bem o quanto nosso time é bom. Vamos arrasar amanhã
