### ISSUE TITLE
Daily Sprint 3 - 7/4 a 13/4

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#87]
Nessa issue estarão todas as dailies remotas da Sprint 2

**Comment by inddiara** [comment]
@lucianaribeiro To mexendo no backlog do produto, definindo quais são nossos épicos e features

**Comment by Ed-vL** [comment]
@lucianaribeiro Fechei a issue com a Sofia. Tratei de paths pra gaia bot, readme e pequenos bugs.

**Comment by micaellagouveia** [comment]
Ontem eu e os meninos conseguimos salvar no banco os dados, e verificar se o local já esta no banco, para dps fazer a requisição na API caso precise. Hoje, eu e o samuel estamos fazendo o teste que falta na issue da integração do clima com local.

**Comment by AmandaMuniz** [comment]
@lucianaribeiro Hoje eu li mais coisas sobre integração dos microsserviços, mas nada foi decidico ainda. É muito complicado entender e decidir sobre as diferentes integrações, então estou fazendo com calma e cuidado. Agora a noite estou terminando a definição dos padrões de software e devo fechar essa issue. Depois disso vou ficar fazendo os reviews dos PR's.

**Comment by sofiapatrocinio** [comment]
Fechei a issue com o Edu, ontem arrumamos o docker e hoje fizemos a interação com telegram e melhoramos algumas intents e utters

**Comment by lucianaribeiro** [comment]
Estou terminando o plano de comunicação e logo finalizarei o restantes das minhas tarefas.

**Comment by LhTaira** [comment]
Junto com Samuel e Micaella fiz a conexão da API do local com o banco de dados e estava no processo de arrumar bugs até que meu PC ficou inutilizável, então estou fazendo uma formação relâmpago.

**Comment by CalebeRios** [comment]
@lucianaribeiro Essa semana eu fiquei meio ausente do projeto por causa de outros projetos. Mas hoje irei finalizar a pipeline e os reviews dos PR’s
