### ISSUE TITLE
US06: Eu como usuário desejo obter resposta plausíveis sempre que eu falar com a Gaia para que eu possa manter um diálogo 

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#98]
Nessa issue será realizado:
- [x] Gaia responder tudo que é solicitado
- [x] Analisar intents de usuário
- [x] Melhorar fluxo de conversa

Critérios de aceitação:
- [ ] Não deixar o usuário sem uma resposta
- [ ] Apresentar as funcionalidades do bot para que o usuário escolha o que deseja realizar
- [ ] Concordância com a personalidade da Gaia
- [ ] Tempo de resposta inferior a 4s

**Comment by inddiara** [comment]
Seguem alguns links que podem ajudar vocês @sofiapatrocinio @micaellagouveia 

- https://towardsdatascience.com/building-a-conversational-chatbot-for-slack-using-rasa-and-python-part-1-bca5cc75d32f

- https://medium.com/coinmonks/rasa-python-weather-chatbot-51fc218d346d

**Comment by inddiara** [comment]
Esse aqui é sobre user experiencie de chatbots, recomendo muito a leitura @sofiapatrocinio @Ed-vL @micaellagouveia @SamButers @LhTaira 

- https://www.nngroup.com/articles/chatbots/
