### ISSUE TITLE
US07: Eu como usuário desejo que o sistema seja capaz de tratar os dados referentes ao clima para que eu possa entende-los

### ISSUE THREAD

**Issue by lucianaribeiro** [fga-eps-mds/2019.1-Gaia#99]
Nessa issue será realizado:
- [x] Padronizar model do clima
- [x] Analisar variáveis de posição das nuvens para tradução
- [x] Tratar variáveis no S.I.

Critérios de aceitação:
- [x] Estar testado
- [x] Conversão de medidas funcionando de acordo com o S.I
- [x] Medidas de temperatura em Celsius
- [x] Velocidade em m/s e nós
- [x] Pressão atmosférica em atm
- [x] Data em dd/mm/aaaa
- [x] Fuso horário UTC/GMT -3 
- [x] Formato de horas em HH:SS

**Comment by sofiapatrocinio** [comment]
Referente a data, a API não fornece esses dados. Como seria esse tratamento?

**Comment by inddiara** [comment]
Update: A API fornece os dados em formato unix timestamp, 
exemplo "sunrise":1435610796,"sunset":1435650870

Logo, vocês terão que formatar esse dado conforme modelo de data e hora.
Links de ajuda: 
- https://stackoverflow.com/questions/847185/convert-a-unix-timestamp-to-time-in-javascript
- https://www.unixtimestamp.com/index.php
